FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY app.js /usr/share/nginx/html/app.js
COPY cropped-favicon-32x32.png /usr/share/nginx/html/cropped-favicon-32x32.png
